### ISSUE TITLE
Grammatical error in German translation of form validation

### ISSUE THREAD

**Issue by GitRon** [carltongibson/django-unique-user-email#13]
Hi @carltongibson!

Honestly not sure if I'm ringing the bell on the right door here. I just installed your package (works amazing!) but found an error with the German translation in the case that the validation gets triggered.

> Benutzer mit diesem E-Mail-Adresse existiert bereits.

The word "address" is femine, therefore it needs to be "diese" instead of "diesem". I googled around but couldn't find a place where I can create a PR. Is this maybe some magic where the field gets injected in the translation string? 🤔 

Best from Cologne  
Ronny

**Comment by carltongibson** [comment]
Ooh, good one. Is that a Django translation? 

So... 

https://app.transifex.com/django/django/translate/#de/contrib-auth/12378826

... perhaps? 🤔

**Comment by GitRon** [comment]
Thx for the reply! It seems the tool requires payment? Whats the best way of contributing here?

**Comment by carltongibson** [comment]
> ... requires payment...

It shouldn't do. 

Perhaps asking @claudep to add you to the German team? 

Here's the relevant page from the Django docs: https://docs.djangoproject.com/en/5.1/internals/contributing/localizing/#s-translations

You should be able to get through to the _Join this team_ step, and then I think @claudep has to OK you.

**Comment by GitRon** [comment]
You are right! There's a well-hidden button for an open-source account 😅 

Great, found the button and will fix the translation once I'm in 👌 

Since this is not related to this package, we could close this ticket, right?

**Comment by carltongibson** [comment]
I'll just wait to see if all can be resolved, or if there's some issue coming out of trying to wham "email address" where only "username" used to go. 🤔

**Comment by claudep** [comment]
About Transifex team approval: normally team coordinators are approving join requests. I only intervene when no coordinators are active.

About the issue, the problematic string is `"%(model_name)s with this %(field_labels)s already exists."` (see https://app.transifex.com/django/django/translate/#de/core/25257941). It's a tricky string to translate due to the variable possible content of `model_name` and `field_labels`. The best thing to do in this case is to use a defensive approach. In French, we translated it like it was "An object %(model_name)s with the fields %(field_labels)s already exists", to avoid such issues, as you never know what can contain `field_labels`. Each language has to find a way to translate it so it can accomodate the widest possible types of content.

**Comment by GitRon** [comment]
Hi @claudep! Thanks for the hint! I went to the [Django internationalisation forum](https://forum.djangoproject.com/t/grammatical-error-in-german-translation-of-form-validation/34478) and created a post so everything can go it's way.

**Comment by carltongibson** [comment]
Thanks both. Will close this. ✊
